name: Unit Test

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Docker image and run tests
        run: docker build . --file Dockerfile --tag pyspark-test:$(date +%s)
